@startuml

interface IAppleLine {

    + void usbInputHeader();
    + void aTypeOutputHeader();
}

interface IHuaweiLine {
    + void usbInputHeader()
    + void cTypeOutputHeader()
}

class FoxconnAppleLine implements IAppleLine {
    + void usbInputHeader()
    + void aTypeOutputHeader()
}

class HuaweiLineAdapter extends FoxconnAppleLine implements IHuaweiLine {
    + void cTypeOutputHeader()
}

@enduml