@startuml

interface IListener {

    void onStart()
    void onCreate()
    void onChange()
    void onDelete()
    void onStop()
}

class ListenerAdaptor implements IListener{
    + void onStart()
    + void onCreate()
    + void onChange()
    + void onDelete()
    + void onStop()
}

class ListenerMonitor extends ListenerAdaptor{
    + void onStart()
    + void onStop()
}

@enduml