@startuml
interface Vehicle {
    void doSomething()
}
class Vehicle550 implements Vehicle {
    +void doSomething()
}
class Vehicle551 implements Vehicle {
    +void doSomething()
}
class Vehicle552 implements Vehicle {
    +void doSomething()
}
class Vehicle553 implements Vehicle {
    +void doSomething()
}

interface VehicleFactory {
    Vehicle createVehicle(String version)
}
class EvenVehicleFactory implements VehicleFactory {
    +Vehicle createVehicle(String version)
}
class OddVehicleFactory implements VehicleFactory {
    +Vehicle createVehicle(String version)
}

VehicleFactory  <..* Vehicle
@enduml